/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_school21_SmartCalc_model_CalculatorModel */

#ifndef C_SRC_CALCULATOR_MODEL_H
#define C_SRC_CALCULATOR_MODEL_H
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_school21_SmartCalc_model_CalculatorModel
 * Method:    evaluateExpression
 * Signature: (Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL
Java_edu_school21_SmartCalc_model_CalculatorModel_evaluateExpression(JNIEnv *,
                                                                     jobject,
                                                                     jstring,
                                                                     jstring);

/*
 * Class:     edu_school21_SmartCalc_model_CalculatorModel
 * Method:    buildAGraph
 * Signature: (Ljava/lang/String;[D)[D
 */
JNIEXPORT jdoubleArray JNICALL
Java_edu_school21_SmartCalc_model_CalculatorModel_buildAGraph(JNIEnv *, jobject,
                                                              jstring,
                                                              jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif  // C_SRC_CALCULATOR_MODEL_H
